
export type SleeperPlayer = {
	status: string | null;
	date: string | null;
	stats: {
		rush_lng: number;
		pass_int: number;
		pass_air_yd: number;
		pos_rank_std: number;
		gp: number;
		rank_half_ppr: number;
		tm_def_snp: number;
		gms_active: number;
		penalty: number;
		pass_sack_yds: number;
		rank_std: number;
		pos_rank_half_ppr: number;
		pass_ypc: number;
		pass_lng: number;
		idp_tkl: number;
		pass_td_40p: number;
		pass_rush_yd: number;
		pts_std: number;
		tm_st_snp: number;
		pass_rtg: number;
		bonus_pass_cmp_25: number;
		rush_fd: number;
		idp_tkl_solo: number;
		pass_att: number;
		fum_lost: number;
		rush_att: number;
		pass_rz_att: number;
		rush_ypa: number;
		bonus_pass_yd_300: number;
		pass_td_50p: number;
		gs: number;
		tm_off_snp: number;
		pos_rank_ppr: number;
		rank_ppr: number;
		pass_sack: number;
		penalty_yd: number;
		off_snp: number;
		rush_tkl_loss_yd: number;
		pass_cmp: number;
		cmp_pct: number;
		rush_yac: number;
		rush_2pt: number;
		pts_half_ppr: number;
		pts_idp: number;
		pass_ypa: number;
		pass_cmp_40p: number;
		pass_fd: number;
		pass_yd: number;
		rush_rz_att: number;
		rush_rec_yd: number;
		pass_td: number;
		bonus_fd_qb: number;
		rush_yd: number;
		rush_40p: number;
		fum: number;
		pass_td_lng: number;
		pts_ppr: number;
		pass_inc: number;
		rush_tkl_loss: number;
		[key: string]: any;
	};
	category: string;
	last_modified: number;
	week: number | null;
	sport: string;
	season_type: string;
	season: string;
	player: {
		fantasy_positions: string[];
		first_name: string;
		injury_body_part: string | null;
		injury_notes: string | null;
		injury_start_date: string | null;
		injury_status: string | null;
		last_name: string;
		metadata: {
			channel_id: string;
			rookie_year: string;
			[key: string]: any;
		} | null;
		news_updated: number;
		position: string;
		team: string;
		team_abbr: string | null;
		team_changed_at: number | null;
		years_exp: number;
	};
	team: string;
	player_id: string;
	updated_at: number;
	game_id: string;
	company: string;
	opponent: string | null;
	week_shard: string | null;
};

export default SleeperPlayer;
